from gym_gazebo.envs.gazebo_env import GazeboEnv

# Turtlebot
from gym_gazebo.envs.gazebo_maze_turtlebot_lidar import GazeboMazeTurtlebotLidarEnv
from gym_gazebo.envs.gazebo_circuit_turtlebot_lidar import GazeboCircuitTurtlebotLidarEnv
from gym_gazebo.envs.gazebo_circuit2_turtlebot_lidar import GazeboCircuit2TurtlebotLidarEnv
from gym_gazebo.envs.gazebo_circuit2_turtlebot_lidar_nn import GazeboCircuit2TurtlebotLidarNnEnv
from gym_gazebo.envs.gazebo_circuit2c_turtlebot_camera_nn import GazeboCircuit2cTurtlebotCameraNnEnv
from gym_gazebo.envs.gazebo_round_turtlebot_lidar import GazeboRoundTurtlebotLidarEnv
#SnakeMonster
from gym_gazebo.envs.gazebo_circuit2_snakemonster_lidar import GazeboCircuit2SnakeMonsterLidarEnv
from gym_gazebo.envs.gazebo_snake_lidar import GazeboSnakeLidarEnv
from gym_gazebo.envs.gazebo_circuit2c_snakemonster_camera_nn import GazeboCircuit2cSnakeMonsterCameraNnEnv

# Erle-Copter
from gym_gazebo.envs.gazebo_erlecopter_hover import GazeboErleCopterHoverEnv

#Erle-Rover
from gym_gazebo.envs.gazebo_maze_erlerover_lidar import GazeboMazeErleRoverLidarEnv
